config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  root to: redirect('admin', status: 302)

  namespace :admin do
    resources :badges, only: [:index]
    get '/', to: 'dashboard#index'
    get '/search', to: 'search#index'
    get '/reports(/:action)', controller: 'reports'
    resources :users, except: [:destroy]
    resources :learning_registry_submissions, only: [:index, :update]
    resources :resources do
      resources :reviews
      member do
        match 'flags', via: [:put, :patch]
      end
    end
    resources :tag_groups, except: [:destroy]
    resources :search_configs, except: [:destroy]
    resources :search_queries, only: [:index]
    resources :suggested_searches, only: [:index] do
      collection do
        get 'edit'
        post 'edit', action: 'update'
      end
    end
    resources :articles, except: [:destroy] do
      post :publish, on: :member
    end
    resources :collection_groups, only: [:index, :create, :edit, :update]
    resources :featured_collection_groups, only: [:index, :create, :update, :destroy] do
      collection do
        post :reorder
      end
    end
    resources :chats, only: [:index, :create, :edit, :update] do
      member do
        put 'archive'
      end
    end
    resources :chat_promos, only: [:index, :create, :destroy] do
      collection do
        post :cancel_message
      end
    end
    resources :schedule_occurrence, only: [:update]
  end

  devise_for :users, :controllers => { confirmations: 'confirmations' }

  mount ApiManager => '/'

  mount GrapeSwaggerRails::Engine, at: "/v1/documentation" if Secrets.swagger

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Searchable

  belongs_to :user

  INDEX_COUNTER = 1
  settings ::Searchable::SETTINGS

  def name
    title
  end

  def published?
    published_at.present?
  end

  def publish!
    update!(published_at: Time.zone.now)
  end

  def as_indexed_json options={}
    attributes.merge({
      'published' => published_at.nil? ? false : true
    })
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

  before_action :authorize_superuser!

  def index
    if params[:articles]
      sort = filters[:sort]
      channel = filters[:channel]
      published = filters[:published]
      featured = filters[:featured]
      user_id = filters[:user_id]
    else
      sort = "Created"
      channel = "Both"
      published = "Both"
      featured = "Both"
      user_id = nil
    end

    @articles =
      Article
        .includes(:user)
        .page(params[:page])
        .per(50)

    case sort
    when "Published"
      @articles = @articles.order(published_at: :desc)
    else
      @articles = @articles.order(created_at: :desc)
    end

    case channel
    when "Advisor"
      @articles = @articles.where(channel: "advisor")
    when "Blog"
      @articles = @articles.where(channel: "blog")
    end

    case published
    when "Published"
      @articles = @articles.where.not(published_at: nil)
    when "Unpublished"
      @articles = @articles.where(published_at: nil)
    end

    case featured
    when "Featured"
      @articles = @articles.where(featured: true)
    when "Not Featured"
      @articles = @articles.where(featured: false)
    end

    if user_id.present?
      @articles = @articles.where(user_id: user_id)
    end
  end

  def new
    @article = Article.new(user: current_user)
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to [:admin, @article]
    else
      render action: 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to [:admin, @article]
    else
      render action: 'edit'
    end
  end

  def publish
    @article = Article.find(params[:id])
    @article.publish!
    redirect_to [:admin, @article]
  end

  private

  def article_params
    params
      .require(:article)
      .permit(
        :channel,
        :user_id,
        :title,
        :body,
        :excerpt,
        :featured,
        :ipad_app_featured,
        :ipad_app_position)
  end

  def filters
    params.require(:articles).permit(
      :sort,
      :channel,
      :published,
      :featured,
      :user_id
    )
  end
end

app/views/admin/articles/_form.html.erb
<style>
  .markdown-preview img { max-width: 100% }
</style>

<div class="row">
  <div id="blog-post-form" class="col-xs-6">

    <%= simple_form_for([:admin, @article]) do |f| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <fieldset>
        <%= f.input :channel, collection: %w(advisor blog), include_blank: false %>
        <%= f.input :user_id, collection: User.for_articles.order(:name), include_blank: false %>
        <%= f.input :title %>
        <%= f.input :body, input_html: { class: "markdown-editor", rows: 16 } %>
        <%= f.input :excerpt,
          hint: "No formatting other than linebreaks allowed.",
          input_html: { rows: 8 } %>
        <%= f.input :featured %>
        <%= f.button :submit %>
      </fieldset>

    <% end %>
  </div>

  <div class="col-xs-6">
    <div class="markdown-helper">
      <div class="markdown-preview-container">
        <div class="markdown-preview-header">
          <h5>Preview</h5>
        </div>
        <div class="markdown-preview"></div>
      </div>
    </div>
  </div>

</div>

<script>
  $('.markdown-editor').wysiwym(Wysiwym.Markdown, {helpEnabled: false});

  var converter = new showdown.Converter();
  var previousValue = null;
  var previewTextarea = $('.markdown-editor');
  var previewOutput = $('.markdown-preview');
  var updateLivePreview = function() {
      var newValue = previewTextarea.val();
      if (newValue != previousValue) {
          previousValue = newValue;
          var newHtml = $("<div>"+ converter.makeHtml(newValue) +"</div>");
          previewOutput.html(newHtml);
      }
  }
  setInterval(updateLivePreview, 200);
</script>

app/views/admin/articles/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Advisor Articles', admin_articles_path %></li>
  <li><%= link_to @article.title, [:admin, @article] %></li>
  <li>Edit</li>
</ul>

<%= render 'form' %>

app/views/admin/articles/index.html.erb
<div id="blog-index">

  <div class="row">
    <div class="span8">

      <div class="page-header">
        <h1>Articles</h1>
      </div>

      <div class="well well-sm">
        <div class="row">
        <%= simple_form_for "articles", method: :get do |f| %>
          <div class="col-xs-1">
            <%= simple_form_ternary f, :channel, %w(Advisor Blog Both) %>
          </div>

          <div class="col-xs-2">
            <%= simple_form_ternary f, :published, %w(Published Unpublished Both) %>
          </div>

          <div class="col-xs-2">
            <%= simple_form_ternary f, :featured, ["Featured", "Not Featured", "Both"] %>
          </div>

          <div class="col-xs-3">
            <%= f.input :user_id,
                        required: false,
                        collection: User.where(id: Article.distinct.pluck(:user_id)).order(:name),
                        selected: params[:user_id],
                        include_blank: true %>
          </div>

          <div class="col-xs-2">
            <%= simple_form_sort f, ["Created", "Published"] %>
          </div>

          <div class="col-xs-1">
            <%= f.button :submit, "Filter" %>
          </div>
        <% end %>
        </div>
      </div>

      <p>
        <%= link_to "New Article",
          new_admin_article_path,
          class: "btn btn-default" %>
      </p>

      <table class="table">
        <tbody>
          <% @articles.each do |article| %>
          <tr>
            <td>
              <h4><%= link_to article.title, [:admin, article] %></h4>
              <div class="blog-created-by">Created by <%= article.user.name %></div>
              <% if article.published_at.present? %>
                <div class="blog-published-date muted">Published:
                  <%= article.published_at.strftime("%b %e %Y %l:%M%P") %></div>
              <% else %>
                <div><span class="label label-warning">Unpublished</span></div>
              <% end %>
            </td>
            <td>
              <% if article.featured? %>
                <span class="label label-info">Featured</span>
              <% end %>
            </td>
            <td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @articles, theme: 'twitter-bootstrap-3' %>

    </div>
  </div>


</div>

app/views/admin/articles/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Articles', admin_articles_path %></li>
  <li>New Article</li>
</ul>

<%= render 'form' %>

app/views/admin/articles/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Advisor Articles', admin_articles_path %></li>
  <li><%= @article.title %></li>
</ul>

<div class="row">
  <div class="col-xs-12">
    <h3><%= @article.title %></h3>
    <p>by <%= @article.user.name %></p>

    <% if @article.published? %>
      <p>Published <%= @article.published_at.strftime("%b %e %Y %l:%M%P") %></p>
    <% end %>

    <div class="btn-group">
      <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
        Actions
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to 'Edit', edit_admin_article_path(@article) %>
        </li>
        <% if @article.published? %>
          <li>
            <%= link_to 'View on participate.com', GenerateUrl.for(@article), target: "_blank" %>
          </li>
        <% end %>
        <li>
          <% if @article.published? %>
            <%= link_to 'Re-Publish', publish_admin_article_path(@article), method: :post, data: { confirm: "Re-publish this article? The published at timestamp will be updated to the current time" } %>
          <% else %>
            <%= link_to 'Publish', publish_admin_article_path(@article), method: :post, data: { confirm: "Publish this article? It will become live to the public." } %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-12">

    <h4>Excerpt</h4>
    <% if @article.excerpt.present? %>
      <%= simple_format(@article.excerpt) %>
    <% else %>
      <div class="alert">
        <strong>This post does not yet have an excerpt</strong>.
        <br>Edit this post to add one.
      </div>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h4>Post Body</h4>
<%= raw Appo::Formatters::Article.markdown.render @article.body %>
  </div>
</div>