config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  root to: redirect('admin', status: 302)

  namespace :admin do
    resources :badges, only: [:index]
    get '/', to: 'dashboard#index'
    get '/search', to: 'search#index'
    get '/reports(/:action)', controller: 'reports'
    resources :users, except: [:destroy]
    resources :learning_registry_submissions, only: [:index, :update]
    resources :resources do
      resources :reviews
      member do
        match 'flags', via: [:put, :patch]
      end
    end
    resources :tag_groups, except: [:destroy]
    resources :search_configs, except: [:destroy]
    resources :search_queries, only: [:index]
    resources :suggested_searches, only: [:index] do
      collection do
        get 'edit'
        post 'edit', action: 'update'
      end
    end
    resources :articles, except: [:destroy] do
      post :publish, on: :member
    end
    resources :collection_groups, only: [:index, :create, :edit, :update]
    resources :featured_collection_groups, only: [:index, :create, :update, :destroy] do
      collection do
        post :reorder
      end
    end
    resources :chats, only: [:index, :create, :edit, :update] do
      member do
        put 'archive'
      end
    end
    resources :chat_promos, only: [:index, :create, :destroy] do
      collection do
        post :cancel_message
      end
    end
    resources :schedule_occurrence, only: [:update]
  end

  devise_for :users, :controllers => { confirmations: 'confirmations' }

  mount ApiManager => '/'

  mount GrapeSwaggerRails::Engine, at: "/v1/documentation" if Secrets.swagger

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  helper_method :user

  def index
    @resources = Resource.where([
      %[
        (
          resources.user_id = ?
          OR
          resources.id IN (
            SELECT DISTINCT reviews.resource_id
            FROM reviews
            WHERE reviews.user_id = ?
          )
        )
        AND kind IN ('app', 'video', 'webpage')
      ],
      user.id,
      user.id
    ])
    .order(updated_at: :desc)
    .page(params[:page])
    .per(20)
  end

  private

  def user
    @user ||= User.find(user_id)
  end

  def user_id
    if current_user.superuser? && user_id_param.present?
      user_id_param
    else
      current_user.id
    end
  end

  def user_id_param
    params.fetch(:admin, {}).fetch(:user_id, nil)
  end

end

app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>

<% if current_user.superuser? %>
  <%= simple_form_for 'admin', method: :get do |f| %>
    <%= f.input :user_id,
                required: false,
                collection: User.active.order(:name),
                selected: user.id,
                include_blank: true %>
  <% end %>
  <script>
    $('#admin_user_id').change(function(){
      this.form.submit();
    });
  </script>
<% end %>

<% if current_user.superuser? && current_user != user %>
  <h3>Reviews for <%= @user.name %></h3>
<% else %>
  <h3>Your Reviews</h3>
<% end %>


<div>
  <button onclick="$('#rsrc-frm').slideToggle(function(){
    $('#resource_url').focus();});return false;"
    class="btn btn-default">New Resource</button>
</div>

<div id="rsrc-frm" style="display:none">
  <hr>
  <%= simple_form_for [:admin, Resource.new] do |f| %>

    <%= f.input :url,
      label: "Resource URL",
      required: false,
      hint: raw('Must include <code>https://</code> or <code>http://</code> in front of any URL you select for web pages, YouTube and Vimeo videos, and app pages from iTunes and Google Play.') %>

    <%= f.button :submit %>
    <button class="btn btn-danger" onclick="$('#rsrc-frm').slideToggle();return false;">Cancel</button>
  <% end %>
  <hr>
</div>


<%= paginate @resources, theme: 'twitter-bootstrap-3' %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Kind</th>
      <th>Name</th>
      <th>Content</th>
      <th>Features</th>
      <th>Engagement</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @resources.each do |resource| %>
      <% reviews = resource.reviews.select{|r| r.fetch('user_id') == user.id} %>
      <tr>
        <td rowspan="<%= reviews.size %>">
          <%= image_tag resource.image_url,
                        style: 'min-width:50px;max-width:50px;',
                        class: 'img-thumbnail' %>
        </td>
        <td class="text-center" rowspan="<%= reviews.size %>">
          <span class="label label-<%= {'ios-app' => 'primary', 'android-app' => 'success', 'video' => 'danger', 'webpage' => 'warning'}.fetch(resource.content_type) %>"><%= resource.content_type.sub('-app', '') %></span>
        </td>
        <td rowspan="<%= reviews.size %>">
          <%= link_to resource.name, [:admin, resource] %>
          <br>
          <a href="<%= resource.url %>" target="_blank" class="text-muted"><small><%= resource.url %></small></a>
        </td>
        <% if reviews.empty? %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        <% else %>
          <% rev = reviews.first %>
          <td><%= rev.fetch('content_score') %></td>
          <td><%= rev.fetch('feature_score') %></td>
          <td><%= rev.fetch('engagement_score') %></td>
          <td><%= link_to "Edit", edit_admin_resource_review_path(resource_id: resource.id, id: rev.fetch('id')) %>
        <% end %>
      </tr>
      <% reviews.drop(1).each do |rev| %>
        <tr>
          <td><%= rev.fetch('content_score') %></td>
          <td><%= rev.fetch('feature_score') %></td>
          <td><%= rev.fetch('engagement_score') %></td>
          <td><%= link_to "Edit", edit_admin_resource_review_path(resource_id: resource.id, id: rev.fetch('id')) %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @resources, theme: 'twitter-bootstrap-3' %>