config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  root to: redirect('admin', status: 302)

  namespace :admin do
    resources :badges, only: [:index]
    get '/', to: 'dashboard#index'
    get '/search', to: 'search#index'
    get '/reports(/:action)', controller: 'reports'
    resources :users, except: [:destroy]
    resources :learning_registry_submissions, only: [:index, :update]
    resources :resources do
      resources :reviews
      member do
        match 'flags', via: [:put, :patch]
      end
    end
    resources :tag_groups, except: [:destroy]
    resources :search_configs, except: [:destroy]
    resources :search_queries, only: [:index]
    resources :suggested_searches, only: [:index] do
      collection do
        get 'edit'
        post 'edit', action: 'update'
      end
    end
    resources :articles, except: [:destroy] do
      post :publish, on: :member
    end
    resources :collection_groups, only: [:index, :create, :edit, :update]
    resources :featured_collection_groups, only: [:index, :create, :update, :destroy] do
      collection do
        post :reorder
      end
    end
    resources :chats, only: [:index, :create, :edit, :update] do
      member do
        put 'archive'
      end
    end
    resources :chat_promos, only: [:index, :create, :destroy] do
      collection do
        post :cancel_message
      end
    end
    resources :schedule_occurrence, only: [:update]
  end

  devise_for :users, :controllers => { confirmations: 'confirmations' }

  mount ApiManager => '/'

  mount GrapeSwaggerRails::Engine, at: "/v1/documentation" if Secrets.swagger

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEX = /\A[-a-z0-9_+'\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  ROLES = ["expert", "content_creator"]

  include Searchable
  include Linkable
  include Subscribable

  attr_accessor :email_notifications

  belongs_to :collaboration

  validates :email, format: EMAIL_REGEX, allow_nil: true
  validate :validate_grade_levels

  def validate_grade_levels
    if grade_levels.detect{ |grade_level| !Appo::ResourceTags::GRADES.include? grade_level }
      errors.add(:grade_levels, :invalid)
    end
  end

  mount_uploader :avatar, AvatarUploader

  has_many :chat_messages
  has_many :collections
  has_many :subscriptions
  has_many :notifications
  has_many :bookmarks
  has_many :scheduled_messages
  has_many :assignments
  has_many :assignment_details
  has_many :assignment_detail_tasks
  has_many :organization_users
  has_many :badge_assertions
  has_many :organizations, through: :organization_users
  has_many :badges, through: :badge_assertions
  has_many :resources

  before_create :update_auth_token!
  before_save :normalize_data
  before_save :maintain_expertise_tags
  before_save :update_notifications
  before_save :request_reconfirmation_if_email_changed
  after_create :assign_preview_collections
  after_commit :reindex_embedded_user_data, on: :update

  INDEX_COUNTER = 3
  settings ::Searchable::SETTINGS do
    mappings do
      indexes :name,
        type: "string",
        fields: {
          name_autocomplete: {
            type: "string",
            analyzer: "autocomplete",
            search_analyzer: "standard"
          },
          name_sort: {
            type: "string",
            analyzer: "lowercase_keyword"
          }
        }
      indexes :bio, type: "string", index: "not_analyzed"
      indexes :profile_photo_url, type: "string", index: "not_analyzed"
      indexes :twitter_username, type: "string", index: "not_analyzed"
      indexes :google_profile_id, type: "string", index: "not_analyzed"
      indexes :external_profile_url_1, type: "string", index: "not_analyzed"
      indexes :external_profile_url_2, type: "string", index: "not_analyzed"
      indexes :expert, type: "boolean"
      indexes :expertise_tags, type: "string", analyzer: "lowercase_keyword"
    end
  end

  INDEXED_FIELDS = %w(
    id
    visible
    name
    lede
    email
    bio
    profile_photo_url
    twitter_username
    google_profile_id
    external_profile_url_1
    external_profile_url_2
    expert
    expertise_tags
  )

  def as_indexed_json(options={})
    {}.tap do |h|
      INDEXED_FIELDS.each do |field|
        h.store(field, self.send(field))
      end
    end
  end


  devise(*[
    :database_authenticatable,
    :lockable,
    :rememberable,
    :timeoutable,
    :trackable,
    :validatable,
    :registerable,
    :confirmable,
    :recoverable
  ])
  include ViflearnPasswordSupport

  VifUserData = Struct.new(
    :district,
    :school,
    :email,
    :first_name,
    :last_name,
    :collection_names
  ) do
    def name
      "#{first_name} #{last_name}".strip
    end
  end

  scope :recent, -> { order(created_at: :desc) }

<<<<<<< HEAD
  def self.vif(greenprintmedia_user_id)
    User.find_by(greenprintmedia_user_id: greenprintmedia_user_id)
=======
  def self.vif(viflearn_user_id)
    User.find_by(viflearn_user_id: viflearn_user_id)
>>>>>>> parent of 0bd3464... customize to greenprintmedia
  end

  def self.try_vif_create(vif_user_data)
    raise "Only in development!" unless Rails.env.development?
    User.transaction do
      vif_create(vif_user_data)
      raise ActiveRecord::Rollback
    end
  end

  def self.vif_create(vif_user_data)
    return false if User.find_by(email: vif_user_data.email)

    transaction do
      cet = false

      user = User.new(email: vif_user_data.email, name: vif_user_data.name)
      user.password = SecureRandom.hex
      user.confirmed_at = Time.now.utc
      user.flags["cet"] = cet
      user.flags["post_import_vif_user"] = true

      if !user.save
        puts "User could not be created: #{user.email}"
        raise ActiveRecord::Rollback
      end

      district = nil
      districts =
        Organization
          .where(type:"District", name: vif_user_data.district).load

      if districts.size < 1
        puts "No district found: #{user.email}"
      elsif districts.size > 1
        puts "Multiple districts found: #{user.email}"
      else
        district = districts.first
      end

      school = nil
      schools =
        Organization
          .where(type:"School", name: vif_user_data.school).load

      if schools.size < 1
        puts "No school found: #{user.email}"
      elsif schools.size > 1
        puts "Multiple schools found: #{user.email}"
      else
        school = schools.first
      end

      if school && district
        if school.district_id != district.id
          puts "School/District mismatch: #{user.email}"
        else
          org_user =
            OrganizationUser.create(
              user: user,
              organization: school,
              role: "learner"
            )

          if !org_user.save
            puts "OrganizationUser could not be created: #{user.email}"
          end
        end
      end

      assigned =
        Assignment.assign(user.email, vif_user_data.collection_names, cet)

      if !assigned
        puts "Assignments could not be created: #{user.email}"
        raise ActiveRecord::Rollback
      end

      puts "Imported #{user.email}"
      true
    end
  end

  def self.for_articles
    where([
      "flags @> ? OR users.id IN (select user_id from articles)",
      %({"active": true})
    ])
  end

  def self.flagged(flag)
    where([
      "flags @> ?",
      %({"#{flag}": true})
    ])
  end

  def self.active
    flagged(:active)
  end

  def self.inactive
    where.not([
      "flags @> ?",
      %({"active": true})
    ])
  end

  def self.autocomplete_search(name)
    search(
      sort: [ { name_sort: "asc" } ],
      size: 6,
      query: {
        match: {
          name_autocomplete: {
            query: name,
            minimum_should_match: "100%"
          }
        }
      }
    ).to_a.map! { |result|
      result
        .fetch("_source")
        .slice(*%w(id name profile_photo_url expert))
    }
  end

  def superuser=(*args)
    # don't do anything
  end

  def really_assign_superuser=(value)
    write_attribute(:superuser, value)
  end

  def display_name
    name || email
  end

  def can?(action, object)
    Ability.new(self).can?(action, object)
  end

  def active?
    flags.fetch("active", false)
  end

  def cet?
    flags.fetch("cet", false)
  end

  def has_role?(role)
    roles.include?(role)
  end

  def expert?
    has_role?("expert")
  end

  def add_role!(role)
    raise "Role #{role} is invalid!" unless ROLES.include?(role)

    roles.push(role).uniq!
    save!
  end

  def remove_role!(role)
    self.roles.delete(role)
    save!
  end

  alias :expert :expert?

  def earned_badge?(badge)
    badge_assertions.where(badge_id: badge.id).exists?
  end

  def make_vifadmin
    organization_users.find_or_create_by(
      organization_id: Appo::Constants::VIF_ORG_ID, role: "admin")
  end

  def vifadmin?
    organization_users.exists?(
      organization_id: Appo::Constants::VIF_ORG_ID, role: "admin")
  end

  def as_json(params = {})
    super({ only: [:id, :name, :bio, :profile_photo_url, :google_profile_id,
      :external_profile_url_1, :external_profile_url_2, :twitter_username] }.merge(params))
  end

  def sign_in_via
    case
    when google_id then "google"
    when twitter_id then "twitter"
    when facebook_id then "facebook"
    when email && encrypted_password then "email"
    else raise "Unhandled option for user id: #{id}"
    end
  end


  # Auth

  def self.for_auth_token(auth_token)
    where("auth_tokens @> ?", [auth_token].to_json).first
  end

  def update_provider_id(provider, provider_id)
    update_attributes "#{provider}_id" => provider_id, :auth_tokens => push_token(Session.token)
  end

  def update_auth_token!
    if persisted?
      push_token(Session.token, true)
    elsif auth_tokens.empty?
      push_token(Session.token)
    end
  end

  def assign_preview_collections
    Collection.preview.each do |preview|
      assignments.create(assignable: preview)
    end
  end

  def token_history
    Secrets.brand.internal_emails.include?(self.email) ? 5 : 2
  end

  def push_token(auth_token, persist = false)
    self.auth_tokens = self.auth_tokens.unshift(auth_token).first(token_history)
    update_attribute(:auth_tokens, self.auth_tokens) if persist

    self.auth_tokens
  end

  def auth_token
    auth_tokens.first
  end

  def email_required?
    true unless facebook_id || google_id || twitter_id
  end

  def password_required?
    if (facebook_id || google_id || twitter_id) && !password.present?
      false
    else
      super
    end
  end

  def editable_collections(public_only = true)
    coll = Collection.where(%[
      user_id = ?
      OR id IN (
        SELECT collaboratable_id FROM collaborations
        WHERE collaboratable_type = ?
        AND collaborator_id = ?
        AND status = 'active'
      )],
      self.id, "Collection", self.id
    )
    coll = coll.where(visibility: "public") if public_only
    coll
  end

  def name
    value = super
    if value.present?
      value
    elsif email.present?
      email.to_s.split("@").first
    else
      nil
    end
  end

  def first_name
    (name || "").split(" ").first
  end

  def can_email?(key)
    email.present? && (disabled_communication & ["all", key.to_s]).empty?
  end

  def notify(key, params)
    Notification.create!(user_id: id, key: key.to_s, params: params)
  end

  def profile_photo_url
    avatar.file.present? ? avatar.url : read_attribute(:profile_photo_url)
  end

  def subscribed_to?(object)
    @_subscribed_to ||=
      subscriptions.pluck(:subscribable_type, :subscribable_id)

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_action :authorize_superuser!, except: [:edit, :update]
  before_action :find_user, only: [:edit, :show, :update]
  before_action :authorize_user!, only: [:edit, :update]

  def index
    @users = User.order(:name).page(params[:page]).per(50)
    if params[:q].present?
      @users = @users.where(
        "name ILIKE :q OR email ILIKE :q", q: "%#{params[:q]}%"
      )
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(new_user_params)
    if @user.persisted?
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
    learning_product_kinds = %w(learning_product activity unit)
    @learning_products = @user.resources.where(kind: learning_product_kinds)

    @assignments =
      @user.assignments.includes(:assignable).map{ |asgn| asgn.assignable }
  end

  def edit
  end

  def update
    @user.attributes = user_params

    if current_user.superuser?
      @user.visible = superuser_user_params[:visible]
      @user.superuser = superuser_user_params[:superuser]

      if @user.access_locked? && superuser_user_params[:access_locked] == '0'
        @user.locked_at = nil
        @user.failed_attempts = 0
      elsif !@user.access_locked? && superuser_user_params[:access_locked] == '1'
        @user.locked_at = Time.zone.now
      end

      if @user.active? && superuser_user_params[:active] == '0'
        @user.flags.delete('active')
      elsif !@user.active? && superuser_user_params[:active] == '1'
        @user.flags.store('active', true)
      end
    end

    if @user.save
      redirect_to (current_user.superuser? ? admin_users_path : admin_path)
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def authorize_user!
    unless current_user.superuser? || ( current_user == @user )
      flash[:alert] = "Sorry, you are not allowed to access that action"
      redirect_to admin_path
    end
  end

  def new_user_params
    params
      .require(:user)
      .permit(*new_user_fields)
  end

  def user_params
    params
      .require(:user)
      .permit(*user_fields)
  end

  def superuser_user_params
    params
      .require(:user)
      .permit(*superuser_user_fields)
  end

  def password_fields
    if params[:user][:password].present?
      [:password, :password_confirmation]
    else
      []
    end
  end

  def new_user_fields
    password_fields + [
      :name,
      :email
    ]
  end

  def user_fields
    new_user_fields + [
      :bio,
      :google_profile_id,
      :twitter_username,
      :external_profile_url_1,
      :external_profile_url_2,
      :picture
    ]
  end

  def superuser_user_fields
    user_fields + [
      :superuser,
      :visible,
      :access_locked,
      :active
    ]
  end

end

app/views/admin/users/_assignments.html.haml
%table.table.table-condensed
  %thead
    %th{ width: "5%" } CET
    %th Name
    %th Assigned Date
  %tbody
    - assignments.sort_by{ |asgn| [asgn.flags["cet"], asgn.name].join }.each do |assignment|
      %tr
        %td= assignment.flags["cet"] ? "✓" : nil
        %td= assignment.name
        %td= assignment.created_at.strftime("%m/%d/%Y")

app/views/admin/users/_badges.html.haml
- user.badge_assertions.each do |ba|
  .badge_assertion
    %a{href: ba.badge.link}
      %span.name
        = ba.badge.name
      %span.date
        = ba.created_at.strftime("%m/%d/%Y")
      %img{src: ba.badge.image_url}
/   render() {
/     return (
/       <a className="badge-preview" href={ Helpers.badgePath(this.props.badge) }>
/         <span className="title">
/           { this.props.badge.name }
/         </span>
/         <hr />
/         <span className="description focused">
/           <span className="inner">
/             <span className="secondary">
/               Earned on
/             </span>
/             <span className="primary">
/               { moment(this.props.badgeAssertion.created_at).format("LL") }
/             </span>
/           </span>
/         </span>
/         <span className="image">
/           <img src={ this.props.badge.image_url } />
/         </span>
/       </a>
/     )
/   }

/ }

app/views/admin/users/_learning_products.html.haml
%table.table.table-condensed
  %thead
    %th Type
    %th Name
    %th Created Date
  %tbody
    - @learning_products.sort_by(&:kind).each do |lp|
      %tr
        %td= lp.kind
        %td
          %a{ href: lp.link }= lp.name
        %td= lp.created_at.strftime("%m/%d/%Y")

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<hr>

<%= simple_form_for [:admin, @user] do |f| %>
  <% if current_user.superuser? %>
    <%= f.input :access_locked?, as: :boolean, label: 'Access locked' %>
    <%= f.input :active?, as: :boolean, label: 'Active' %>
    <%= f.input :visible, as: :boolean %>
  <% end %>

  <% %w(name email bio google_profile_id twitter_username
        external_profile_url_1 external_profile_url_2
        password password_confirmation).each do |field| %>
      <%= f.input field, as: (field == "email" ? :email : nil) %>
  <% end %>

  <%= f.button :submit %>
  <%= link_to "Cancel",
              (current_user.superuser? ? admin_users_path : admin_path),
              class: 'btn btn-danger' %>
<% end %>
<br>
<br>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<div class="well well-sm">
  <%= simple_form_for 'users',
                      method: :get,
                      html: { class: 'form-inline' } do |f| %>

    <%= f.input :q,
                label: false,
                placeholder: 'name or email',
                required: false,
                input_html: {
                  name: 'q',
                  value: params[:q]
                } %>

    <%= f.button :submit, "Search" %>

  <% end %>
</div>

<div>
  <%= link_to "New User", new_admin_user_path, class: 'btn btn-default' %>
</div>

<%= paginate @users, theme: 'twitter-bootstrap-3' %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Info</th>
      <th>Flags</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= image_tag u.profile_photo_url, style: 'width:50px', class: 'img-circle' %></td>
        <td><%= u.name %></td>
        <td>
          <% %w(email facebook_id twitter_id google_id).each do |field| %>
            <% if (value = u.public_send(field)).present? %>
              <b><%= "#{field}:" %></b> <%= value %> <br>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if u.active? %>
            <span class="label label-success">Active</span>
          <% else %>
            <span class="label label-default">Inactive</span>
          <% end %>
          <% if u.visible? %>
            <span class="label label-primary">Visible</span>
          <% end %>
          <% if u.superuser? %>
            <span class="label label-warning">Superuser</span>
          <% end %>
          <% if u.access_locked? %>
            <span class="label label-danger">Locked</span>
          <% end %>
        </td>
        <td>
          <%= link_to "Edit", [:edit, :admin, u] %>
          | <%= link_to "View", [:admin, u] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users, theme: 'twitter-bootstrap-3' %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= simple_form_for [:admin, @user] do |f| %>
  <% %w(name email password password_confirmation).each do |field| %>
    <%= f.input field, as: (field == "email" ? :email : nil) %>
  <% end %>
  <%= f.button :submit %>
  <a href="/admin/users" class="btn btn-danger">Cancel</a>
<% end %>

app/views/admin/users/show.html.haml
%h1 View User

%ul
  %li= "Name: #{@user.name}"
  %li= "Email: #{@user.email}"


<h2>Assignments</h2>
= render "assignments", assignments: @assignments

<h2>Badges</h2>
= render "badges", user: @user

<h2>Learning Products</h2>
= render "learning_products", user: @user